language: r
r:
  - release
  - devel

cache: packages

sudo: required

dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - # activate liblwgeom:
  - sudo ldconfig 
#  - sudo apt-get install ghostscript

warnings_are_errors: true

r_packages:
  - devtools
  - sp
  - rgdal
  - roxygen2
  - rmarkdown
  - covr
  
after_success:
- Rscript -e 'library(covr);codecov()'